apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  type: ClusterIP   # 내부 통신 전용
  selector:
    app: frontend
  ports:
    - name: http
      port: 80       # 내부에서 접근하는 포트
      targetPort: 3000 # 파드에서 열고 있는 포트
