apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # 특정 노드풀로 스케줄링
      nodeSelector:
        ncloud.com/nks-nodepool: np-front
      # NCR Pull Secret 참조
      imagePullSecrets:
        - name: ncr-pull-secret
      containers:
        - name: frontend
          image: <NCR_REGISTRY_HOST>/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
